name: CI testing

on:
  push:
    branches: [main, refactor/cicd]
  pull_request:
    branches: [main]

jobs:
  run-ci-testing:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Check Go
        run: go version

      - name: Prepare CI env
        run: cp example.env .env

      - name: Start DB only
        run: docker compose up -d db

      - name: Wait for DB
        run: |
          until docker compose exec -T db pg_isready -U $DB_USER -d $DB_NAME; do
            sleep 2
          done

      - name: Run tests
        run: go test -v ./test

      - name: Cleanup
        if: always()
        run: docker compose down -v
