name: CI testing

on:
  push:
    branches: [main, refactor/cicd, production, test/unit]
  pull_request:
    branches: [main]

jobs:
  run-ci-testing:
    runs-on: self-hosted

    env:
      DATABASE_URL: postgres://postgres:566493@localhost:5432/file_sharing_test?sslmode=disable&options=-csearch_path=test_schema

    steps:
      - uses: actions/checkout@v4

      - name: Check Go
        run: go version

      - name: Decrypt .env
        run: |
          echo "Decrypting..."
          sops --decrypt --input-type dotenv --output-type dotenv --output .env dev.enc
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}

      - name: Run unit test
        run: |
          echo "There is some unit tests."
          go test -v ./pkg/validation/... ./internal/service/...


